### PR TITLE
Add URLNavigatorDelegate to pre handle URL and view controller presentation

### PR DESCRIPTION
**Pull request by Davidkle**
Add URLNavigatorDelegate to pre handle URL and view controller presentation.

Example use case.
An app has 3 tabs and each tab can be opened with the following urls `/tab1`, `/tab2`, `/tab3`. 

If we have urls `/tab3` and `tab3/123` and we would like to select `tab3` first before continuing to open `tab3/123` then set a delegate to `Navigator` then implement `willOpen(url:)`. In the delegate method, select the desired tab.

### CODE REVIEW

**Comment by devxoul** [comment]
@Davidkle, this is what I was planning to develop for next release! How did you read my mind :) Also I was planning to add `shouldSomething() -> Bool` to prevent push/present/open in some circumstance. (#30) How do you think of it?

**Comment by Davidkle** [comment]
@devxoul I recently ran into this issue so decided to implement it. `shouldSomething() -> Bool` sounds reasonable. I'll add that. I'll also fix the spacing.

**Comment by devxoul** [comment]
Really appreciate it. Could you please write a test for it?

**Comment by devxoul** [comment]
This is implemented in [URLNavigator 2.0.0](https://github.com/devxoul/URLNavigator/releases/tag/2.0.0) :tada:

**Pull request closed without merging**
