### PR TITLE
Add NavigableFactory methods, and map Factory instead of Navigables

### PR DESCRIPTION
**Pull request by juancruzmdq**
Hi,
I created this PR only as a reference to show you some Idea that I had to improve the ViewControllers.
The main idea is map a factory class, instead a URLNavigable.Type , This  allow the user to have different methods to build URLNavigable instances. For example I created this 3:

1) URLNavigableWithClass: Use a URLNavigable.Type to create an instance

``` swift
self.navigator.map("myapp://user/<int:id>", URLNavigableWithClass(UserViewController.self))
```

2) URLNavigableWithStoryboard: Use a storyboard identifier to create the  URLNavigable instance

``` swift
self.navigator.map("myapp://user/<int:id>", URLNavigableWithStoryboard("TestingStoryboard", identifier: "StoryboardIdentifier"))
```

3) URLNavigableWithBlock: Use a block that return a URLNavigable instance

``` swift
self.navigator.map("myapp://user/<int:id>", URLNavigableWithBlock{ URL, values -> URLNavigable in
             // Complex UI Building
            return UserViewController(URL:URL, values:values)!
})
```

Also I created some convenience method to map the URL's with the factory

``` swift
self.navigator.map("myapp://user/<int:id>", URLNavigableWithClass(UserViewController.self))

self.navigator.map("myapp://user/<int:id>", UserViewController.self)
```

``` swift
self.navigator.map("myapp://user/<int:id>", URLNavigableWithStoryboard("TestingStoryboard", identifier: "StoryboardIdentifier"))

self.navigator.map("myapp://user/<int:id>", storyboard: "TestingStoryboard", identifier: "StoryboardIdentifier")
```

``` swift

self.navigator.map("myapp://user/<int:id>", URLNavigableWithBlock{ URL, values -> URLNavigable in
            return UserViewController(URL:URL, values:values)!
})

self.navigator.map("myapp://user/<int:id>"){ URL, values -> URLNavigable in
            // Complex UI Building
            return UserViewController(URL:URL, values:values)!
}
```

What do you think?

Juan C.

### CODE REVIEW

**Comment by jadsonlourenco** [comment]
I'm using this PR and I liked! :+1:
But one thing: I can't **push/present** a new route map to open it later, like on the current version, if push a route it will be opened.

**Comment by juancruzmdq** [comment]
Thanks Jadson!
Sorry but I don't understand what is your issue, can you give me a small example of what is happening?

JC

PS: I made 2 pushes with a small fix to this PR

**Comment by devxoul** [comment]
@juancruzmdq, thanks for your work. Mapping storyboard looks really great!

My opinion:

- `URLNavigableWithClass` is already available at this time without using factory.
- `URLNavigableWithBlock` is also available with using `URLNavigable` initializer: `init(URL:values:)`.
- Then, what we should implement is only storyboard.
    1. It is over-engineering to use factory pattern to deal with just one case.
    2. Storyboard-instanciated view controllers are not able to take advantage of `URL` and `values`. It just "Created". It's better mapping `URLOpenHandler` and use `openURL()` like [this example](https://github.com/devxoul/URLNavigator/blob/88c520083b91e752313f0f481daa918e1ed0023f/README.md#using-with-storyboard).

I think we should do some trick on it.

**Comment by juancruzmdq** [comment]
@devxoul 

* _URLNavigableWithClass is already available at this time without using factory_: You are right, this option already exist

* _URLNavigableWithBlock is also available with using URLNavigable initializer: init(URL:values:):_ Inside the init of the view, you can initialize things related to itself, but the URLNavigableWithBlock gives you the flexibility to initialize/build/inject dependencies other object that are not exclusive to the view.

* _Storyboard-instanciated view controllers are not able to take advantage of URL and values. It just "Created". It's better mapping URLOpenHandler and use openURL() like this example:_ You can use URL and Values in the view controller created with the storyboard. check in the tests "TestingStoryboard":"StoryboardIdentifier" that is an instance of UserViewController . Also, use URLOpenHandler to build the controller is ok, but have two drawbacks: 
1) Force you to include the type of navigation inside the url mapping adding this line _Navigator.push(postViewController)_
2) Mix the executions of block with the navigation between views. Two things that, as I, see are different


I thing that add this factory isn't a big change, and improve the URLNavigable creation. Also, keep backward compatibility

What other option would be useful to create instances from Storyboards?

JC

**Comment by devxoul** [comment]
- Could you please provide me some examples of it?

    > URLNavigableWithBlock gives you the flexibility to initialize/build/inject dependencies other object that are not exclusive to the view.

- How can we get `userID` of `UserViewController` from Storyboard?

    ```swift
    self.navigator.map("myapp://user/<int:id>",
                       storyboard: "TestingStoryboard",
                       identifier: "StoryboardIdentifier",
                       bundle: NSBundle(forClass: self.dynamicType))
    if let userViewController = self.navigator.viewControllerForURL("myapp://user/1") as? UserViewController {
        userViewController.userID // nil (expected: 1)
    }
    ```

What I really want to do is: make it available to use `init(URL:values:)` from Storyboard-instanciated view controllers. I'm trying to do something with `init(coder:)` but it doesn't work as I expected.

The key idea is:

1. Instanciate a view controller from Storyboard using `instantiateViewControllerWithIdentifier()`.
2. Storyboard instanciating will call `init(coder:)`. Keep this `coder` instance somewhere. (such as: associated object, or etc)
3. Initialize a new view controller with `init(URL:values:)`. Pass the `coder` with `values` dictionary.
4. Then developers can call `init(coder:)` from `convenience init(URL:values:)` with `coder` from `values`.

**Comment by jadsonlourenco** [comment]
@juancruzmdq yes, here an example:
```
Navigator.map("myapp://post/<int:id>") { URL, values in
    guard let postID = values["id"] as? Int,
          let postViewController = UIStoryboard(name: "Main", bundle: nil).instantiateInitialViewController()
          else { return false }
    // Push the controller but not open this route yet
    Navigator.push(postViewController)
    return true
}
```
We can **push** a route after map it, then we just **openURL**, you know? But in your PR if we do ```Navigator.push(myViewController)...``` it will open the route in the same time.

**Comment by juancruzmdq** [comment]
* Could you please provide me some examples of it?
I can't think in an example now, but is good to keep the option open

*How can we get userID of UserViewController from Storyboard?
You were right, I thought that send the parameter to the storyboard would be easy. 

I will try to think another option. but I still think that add the factory is a good idea 👍

**Comment by juancruzmdq** [comment]
@jadsonlourenco 
Sorry, but I still can't see the problem

For example in my app I'm doing this:

            Navigator.map("/cities/") { URL, values -> Bool in
                // Create Cities List Controller
                var view:UIViewController = CityList(viewModel: CityListModel(.....))
                // Push the controller but not open this route yet
                Navigator.present(view)
                return true
            }

When I need to present it, I call

```swift
// With this  call the CitiesList is presented
Navigator.openURL("/cities/")
```

What do you mean with _"it will open the route in the same time."_

**Comment by juancruzmdq** [comment]
@devxoul 
The only solution that I can think to send URL and Values  to Storyboard-instanciated view controllers, is move it out of the constructor, and add another method to URLNavigable to register this values after the creation.

**Comment by jadsonlourenco** [comment]
@juancruzmdq I solved my issue, with your PR I need set a **Bool** to return, look:
```
// Before, from current read me
Navigator.map("myapp://post/<int:id>") { URL, values in...

// Then, using your PR
Navigator.map("myapp://post/<int:id>") { URL, values -> Bool in...
```
Thank you for your help, I didn't saw that.

**Comment by devxoul** [comment]
@juancruzmdq,

- Features should not be added if there's no use case. It will increases complexity and may occur unexpected side-effects.
- Factory pattern is useful when there's many dependencies to be decoupled and variety of different environments. In this case, however, there's only a case to consider. This is apparently over-design.

**Comment by devxoul** [comment]
This is implemented in [URLNavigator 2.0.0](https://github.com/devxoul/URLNavigator/releases/tag/2.0.0) :tada:

**Pull request closed without merging**
