### PR TITLE
Resolvable mapping

### PR DESCRIPTION
**Pull request by zdenektopic**
#55

### CODE REVIEW

**Comment by devxoul** [comment]
@zdenektopic, Thanks for your work but this breaks a lot APIs. This is issue is related to Storyboard support, so I'll keep trying to find a better solution.

**Comment by zdenektopic** [comment]
I dont really care about Storyboard support. What do you mean that it breaks a lot of APIs? What APIs?

**Comment by devxoul** [comment]
There is already a function which takes String and closure as parameters. This code will break the code below.

```swift
// ambiguous definition
Navigator.map("navigator://alert") { _ in
  doSomething()
}
```

**Comment by zdenektopic** [comment]
I see, havent seen it in docs, neither in code I think.

**Comment by zdenektopic** [comment]
Ok found it. But this doesn't return  UIViewController but is supposed to take some action, which is not really what is intended.

**Comment by devxoul** [comment]
Yeap. It just performs action and returns nothing. This is for selecting tab bar or changing root view controller, etc.

**Comment by zdenektopic** [comment]
So it is just issue with api naming. Maybe rename the mapping method for open to `mapOpen` or something like that?

**Comment by devxoul** [comment]
That breaks many code too. I don't have plan to support this feature in near future. It maybe available in next major update with some philosophic consideration. At this time I'd recommend you to fork this repo and use that instead.

**Pull request closed without merging**
