### PR TITLE
Add support for setting navigator scheme.

### PR DESCRIPTION
**Pull request by devxoul**
Another implementation for #10

```swift
Navigator.scheme = "myapp"
Navigator.map("/user/<int:id>", UserViewController.self)
Navigator.map("/alert") { _ in print("Alert") }

Navigator.push("/user/123")
Navigator.present("/user/123")
Navigator.open("/alert?title=Hi")
```

this is equivalent to:

```swift
Navigator.map("myapp://user/<int:id>", UserViewController.self)
Navigator.map("myapp://alert") { _ in print("Alert") }

Navigator.push("myapp://user/123")
Navigator.present("myapp://user/123")
Navigator.open("myapp://alert?title=Hi")
```

Example for multiple navigators:

```swift
let facebookNavigator = URLNavigator()
facebookNavigator.scheme = "fb"
facebookNavigator.map("/post/<id>", PostViewController.self) // "fb://post/<id>"

let instagramNavigator = URLNavigator()
instagramNavigator.scheme = "instagram"
instagramNavigator.map("/post/<id>", PostViewController.self) // "instagram://post/<id>"
```

### CODE REVIEW

**Comment by juancruzmdq** [comment]
Is better, but you always have to call URLWithScheme, before call normalizedURL. I think that build the url with the scheme is part of the normalization.


```swift
let URLPatternWithScheme = URLNavigator.URLWithScheme(self.scheme, URLPattern)
let URLString = URLNavigator.normalizedURL(URLPatternWithScheme).URLStringValue
```

What I would do is change this to method, from static, to instance, and do something like

```swift
let URLString = self.normalizedURL(URLPattern).URLStringValue

func normalizedURL(URLPattern){
        let URLPatternWithScheme = URLNavigator.URLWithScheme(self.scheme, URLPattern)
        ...
}
```

**Comment by devxoul** [comment]
Totally agree with code duplications. But, why I want to keep `normalizedURL()` static method is to make utility functions context-free. If `normalizedURL()` become instance method, this will have context of its instance properties that may cause unexpected output.

How about providing `scheme` as a parameter of `normalizedURL`?

**Comment by juancruzmdq** [comment]
yes, could be an option

**Comment by devxoul** [comment]
@juancruzmdq, I've made some changes on `normalizedURL()` function to have `scheme` as an optional parameter. And added "Setting Default Scheme" section to README file. If it looks good, I'll merge this PR and make a new release :)

**Comment by juancruzmdq** [comment]
Hi, 
yes, looks good

**Comment by devxoul** [comment]
@juancruzmdq [0.6.0](https://github.com/devxoul/URLNavigator/releases/tag/0.6.0) has been released :smile:

**Pull request merged**
