### PR TITLE
Improve topMost computed var with all windows checking

### PR DESCRIPTION
**Pull request by bill350**
Some applications have specific behavior with multiple windows. This is true specifically when you integrate some Ad SDK (like... Google Ads) or Passcode behavior. It consist of using an UIWindow with no specific rootViewController but just with a view inside.

Here an example with Google-Mobile-Ads-SDK :

The app start and Google show an interstitial, here the view hierarchy :
start

When the interstitial is hidden, the UIWindow go back to first position into the view hierarchy :
afterinterstitialdismiss

It is just an example and other Ad SDKs run like that. Some Passcode or login behavior run also like this.

So **because we want the topMost controller of the entire app**, I improve the `topMost` computed var to loop into all windows of the current app, and stop when a `rootViewController` is found into an UIWindow.

Another approach is to use the `keyWindow` property but I had some issue in the past because `makeKeyAndVisible` is not necessary called...

What do you think about it ?

### CODE REVIEW

**Comment by iGranDav** [comment]
Indeed using the first window in hierarchy does not seams to be a viable way. Nice PR 👍

**Comment by devxoul** [comment]
@bill350, aren't there other windows which have `rootViewController` as well?

**Comment by bill350** [comment]
@devxoul Yes, it is possible that any `UIWindow` have a `rootViewController`. But if we follow the initial code logic of the computed property, it has to be renamed with `firstMost` instead of `topMost`.

My improvement not change the initial logic. If we want to go further, we have to propose some options on the configuration of the URLNavigator : `keyWindowBased`, `firstMost`, `topMost`... 

But anyway, I think it is better with this modification now. And other specific behaviors could be added with another PR.

What do you think ?

**Comment by devxoul** [comment]
@bill350 That makes sense. I'll merge this PR when the test passes. Thanks for your work!

**Comment by devxoul** [comment]
@bill350, Your commit has been shipped with [1.1.2 release](https://github.com/devxoul/URLNavigator/releases/tag/1.1.2) and will be available on CocoaPods soon. Thanks for your contribution :tada:

**Comment by bill350** [comment]
Good ! Thank you @devxoul 😊 🍻

**Pull request merged**
