### PR TITLE
tvOS compatibility

### PR DESCRIPTION
**Pull request by bill350**
Related to the isssue https://github.com/devxoul/URLNavigator/issues/66 , I've created a tvOS branch ready to use and to merge 🚀 

What do you think @devxoul ?
I have just some doubt about Travis CI configuration file 🤔 . 

🍻

### CODE REVIEW

**Comment by devxoul** [comment]
I can't merge your pull request because there's too many diffs (including unnecessary changes). I'm going to work on it now.

**Comment by bill350** [comment]
I don't' understand.
There is only changes for the sample demo code, because of two new targets. Source code of URLNavigator itself was not modified.
Did you test it ?

**Comment by devxoul** [comment]
You changed a lot of file including `.travis.yml` quotes, and created many space-only lines :( And creating a new product just for tvOS (`URLNavigator-tvOS`) is not good.

I was trying to get rid of the xcodeproj file from the git repository to migrate the whole directory structure to Swift Package Manager's. So I can easily add a tvOS support.

**Comment by devxoul** [comment]
URLNavigator [1.2.5](https://github.com/devxoul/URLNavigator/releases/tag/1.2.5) is released. It contains tvOS :)

**Pull request closed without merging**
