### PR TITLE
Improve searching top most view controller logic.

### PR DESCRIPTION
**Pull request by RyogaK**
@devxoul 
It is not guaranteed that keyWindow is at the first of windows. So, I tried to filter out windows that are not key window from currentWindows.

Tell me what you think.

Thanks.

### CODE REVIEW

**Comment by devxoul** [comment]
What problem did you want to solve is?

**Comment by RyogaK** [comment]
@devxoul Sometimes, UIApplication#windows[0] is not the key window.

e.g.
- The developer may use multiple windows properly. (e.g. Add a window for viewing debugging utility.)
- Google Mobile Ads will adds an invisible window (That is for the view controller named GADxxxxxxViewController).

The view controller won't be push(or present) from the intended view controller.
Usually, developers hope to push the view controller by the now appearing window.

Thanks.

**Comment by devxoul** [comment]
It would be great if this PR contains test cases :)

**Comment by RyogaK** [comment]
Close because it is not likely to be merged.

**Pull request closed without merging**
